### ISSUE TITLE
Seeing the same spikes

### ISSUE THREAD

**Issue by khous** [RalfJL/CCS811FirmwareUpdate#1]
Are you still working on this? I'm trying to use these sensors as well. Happy to share notes

**Comment by RalfJL** [comment]
Sorry, for being late.
I stopped working on that sensor. It gives you only the VTOC and calculates the CO2 value from that, but CO2 is of no real value. 
E.g. using a deodorant increases the VTOC and lets the CO2 value jump through the roof.
