### ISSUE TITLE
Answer regarding your question "Someone else having this experience?"

### ISSUE THREAD

**Issue by samazw** [RalfJL/CCS811FirmwareUpdate#3]
Hey Ralf [not an issue]

you mention the behavior of your CCS811 in the README.md. I had the same issue. 
Using Maarten´s CCS811 firmware updater to v2.0.1 ( https://github.com/maarten-pennings/CCS811 ) resolved this, though I cannot see any relationship between changes from v2.0.0 to 2.0.1 and the sensor behavior causing peaks.

Hope this helps.

**Comment by RalfJL** [comment]
Thanks a lot, I will give it a try.
